language: php

sudo: false

addons:
  postgresql: "9.5"

cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.npm

php:
  - 7.1
  - 7.2

services:
  - mysql

env:
  - DB=pgsql MOODLE_BRANCH=MOODLE_35_STABLE CI_PLUGIN=2
  - DB=pgsql MOODLE_BRANCH=MOODLE_36_STABLE CI_PLUGIN=2
  - DB=pgsql MOODLE_BRANCH=MOODLE_37_STABLE CI_PLUGIN=2
  - DB=pgsql MOODLE_BRANCH=MOODLE_38_STABLE CI_PLUGIN=2
  - DB=pgsql MOODLE_BRANCH=master CI_PLUGIN=2
  - DB=mysqli MOODLE_BRANCH=MOODLE_35_STABLE CI_PLUGIN=2
  - DB=mysqli MOODLE_BRANCH=MOODLE_36_STABLE CI_PLUGIN=2
  - DB=mysqli MOODLE_BRANCH=MOODLE_37_STABLE CI_PLUGIN=2
  - DB=mysqli MOODLE_BRANCH=MOODLE_38_STABLE CI_PLUGIN=2
  - DB=mysqli MOODLE_BRANCH=master CI_PLUGIN=2

matrix:
  exclude:
    - php: 7.1
      env: DB=mysqli MOODLE_BRANCH=master CI_PLUGIN=2
    - php: 7.1
      env: DB=pgsql MOODLE_BRANCH=master CI_PLUGIN=2
  include:
    - php: 7.3
      env: DB=mysqli MOODLE_BRANCH=MOODLE_37_STABLE CI_PLUGIN=2
    - php: 7.3
      env: DB=pgsql MOODLE_BRANCH=MOODLE_37_STABLE CI_PLUGIN=2
    - php: 7.3
      env: DB=mysqli MOODLE_BRANCH=MOODLE_38_STABLE CI_PLUGIN=2
    - php: 7.3
      env: DB=pgsql MOODLE_BRANCH=MOODLE_38_STABLE CI_PLUGIN=2
    - php: 7.3
      env: DB=mysqli MOODLE_BRANCH=master CI_PLUGIN=2
    - php: 7.3
      env: DB=pgsql MOODLE_BRANCH=master CI_PLUGIN=2

before_install:
  - phpenv config-rm xdebug.ini
  - cd ../..
  - echo $CI_PLUGIN
  - git clone --mirror 'https://github.com/moodlehq/moodle-behat-extension.git' '/home/travis/.composer/cache/vcs/git-github.com-moodlehq-moodle-behat-extension.git/' || true
  - nvm install 8.9;
  - nvm use 8.9;
  - composer create-project -n --no-dev --prefer-dist moodlerooms/moodle-plugin-ci ci ^2;
  - export PATH="$(cd ci/bin; pwd):$(cd ci/vendor/bin; pwd):$PATH"

install:
  - moodle-plugin-ci install -vvv

script:
  - moodle-plugin-ci phplint
# - moodle-plugin-ci phpcpd
  - moodle-plugin-ci phpmd
  - moodle-plugin-ci codechecker
  - moodle-plugin-ci validate
  - moodle-plugin-ci savepoints || travis_terminate 1;
  - moodle-plugin-ci mustache || travis_terminate 1;
  - moodle-plugin-ci grunt || travis_terminate 1;
  - moodle-plugin-ci phpunit
  - moodle-plugin-ci behat
